apiVersion: v1
kind: Service
metadata: 
  name: cd-test-service
spec:
  type: NodePort
  selector:
    app: cd-test
  ports: 
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30009
